### ISSUE TITLE
大神：Configuration里添加多个窗帘有报错出现，如何添加多个窗帘？

### ISSUE THREAD

**Issue by jarod360** [tiandeyu/mijia_curtain#16]
大神：Configuration里添加多个窗帘有报错出现，如何添加多个窗帘？，只能显示最后一个窗帘

**Comment by jarod360** [comment]
已搞定

**Comment by jarod360** [comment]
老大添加的时候提示这个错误，该如何修复。该实体 (“cover.smartj_ktcl”) 没有 unique ID，因此无法由 UI 管理其设置。请参阅 [文档](https://www.home-assistant.io/faq/unique_id) 以详细了解。

**Comment by tiandeyu** [comment]
这个报错应该不影响使用，设置了name就行了

**Comment by jarod360** [comment]
https://home.miot-spec.com/s/smartj.curtain.sjdt82  这是支持链接，测试控制，状态都正常，就是出现 没有 unique ID
