### ISSUE TITLE
杜亚M1通过HA添加成功后，在Homekit中不支持百分比

### ISSUE THREAD

**Issue by w4mxl** [tiandeyu/mijia_curtain#3]
![IMG_2809](https://user-images.githubusercontent.com/3645496/104202270-aadd6c00-5465-11eb-8026-224488304ae2.JPEG)

👆上图左边是我之前通过购买其它模块替换了杜亚M1的模块后借助MQTT实现的，右图是通过您这边的插件添加后实现的。

我发现在HA上都是可以控制的（开、关、停止、百分比），但是在 HomeKit 上您的插件好像只能切换开和关。
请问这个可以优化一下吗？

**Comment by tiandeyu** [comment]
修复好了，但是HA里面样式会有变化，默认的窗帘(curtain)是上下运动的动画，如果要改成左右运动可以自行去HA Configuration-Customizations-对应的设备-设置device class为Gate或者Door

**Comment by w4mxl** [comment]
> 修复好了，但是HA里面样式会有变化，默认的窗帘(curtain)是上下运动的动画，如果要改成左右运动可以自行去HA Configuration-Customizations-对应的设备-设置device class为Gate或者Door

好的，晚上试下。

谢谢！

**Comment by w4mxl** [comment]
我这边就沿用了默认的窗帘(curtain)是上下运动的动画，也挺好的。

不过测试后发现还有一个小问题，就是在 Homekit 中「打开」窗帘的时候，即使我的左右开合帘已经完全打开，也会一直显示正在打开的状态。希望能帮忙看下这个问题。

![WechatIMG417](https://user-images.githubusercontent.com/3645496/104392881-0dc22680-557e-11eb-8058-38d1ac549d38.jpeg)

**Comment by tiandeyu** [comment]
刷新时间最长30s，所以会有一定的延迟，更新下最新版，修复了一些状态问题

**Comment by w4mxl** [comment]
> 刷新时间最长30s，所以会有一定的延迟，更新下最新版，修复了一些状态问题

我早上出门前是更新了目前最新版（你昨晚 commit 后的）。
不是因为刷新间隔的延迟，因为隔了很久（5min、10min...)，还是会显示「正在打开...」哦

**Comment by tiandeyu** [comment]
感谢支持，最新版已经修复

**Comment by khalaa** [comment]
> 我这边就沿用了默认的窗帘(curtain)是上下运动的动画，也挺好的。
> 
> 不过测试后发现还有一个小问题，就是在 Homekit 中「打开」窗帘的时候，即使我的左右开合帘已经完全打开，也会一直显示正在打开的状态。希望能帮忙看下这个问题。@tiandeyu
> 
> ![WechatIMG417](https://user-images.githubusercontent.com/3645496/104392881-0dc22680-557e-11eb-8058-38d1ac549d38.jpeg)
同样的问题，是否已经解决？

**Comment by tiandeyu** [comment]
我没能够复现这个故障，更新下最新版试试
