### ISSUE TITLE
更新 版本 hass core-2021.6.2后无法找到集成，检查报错如下：

### ISSUE THREAD

**Issue by 9609759** [tiandeyu/mijia_curtain#8]
Platform error cover.mijia_curtain - Integration 'mijia_curtain' not found.
Platform error cover.mijia_curtain - Integration 'mijia_curtain' not found.
Platform error cover.mijia_curtain - Integration 'mijia_curtain' not found.

根据版本号要求已经添加了版本号   "version": "1.0.0"，依然报错，请问该怎么解决。

{
  "domain": "mijia_curtain",
  "name": "Mijia Curtain",
  "documentation": "https://www.natic.cn",
  "version": "1.0.0"
  "dependencies": [],
  "codeowners": ["@natic"],
  "requirements": []
}

**Comment by tiandeyu** [comment]
先屏蔽configuration,重启之后再添加配置

**Comment by 9609759** [comment]
已经试图将configuration内的配置注释掉，重新启动hass，问题依然会存在。我在官方文档中看到“移除已弃用的 YAML 导入的集成"  是否是因为此原因造成的。

**Comment by tiandeyu** [comment]
好的，我尽快升级看一下

**Comment by tiandeyu** [comment]
我已经升级，工作正常，你尝试重新安装一下插件

**Comment by 9609759** [comment]
重新安装后解决问题，谢谢！
